# ┌─────────────────────────────────────────────────────────────────┐
# │ Docker Aliases — Oh-My-Zsh docker + docker-compose plugin style │
# └─────────────────────────────────────────────────────────────────┘

alias d="docker"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dim="docker images"
alias drm="docker rm"
alias drmi="docker rmi"
alias dstop="docker stop"
alias dkill="docker kill"
alias dlogs="docker logs -f"
alias dexec="docker exec -it"
alias dpu="docker pull"
alias dbl="docker build"
alias dit="docker image tag"

alias dcin="docker container inspect"
alias dcls="docker container ls"
alias dclsa="docker container ls -a"
alias dpo="docker container port"
alias dr="docker container run"
alias drit="docker container run -it"
alias drs="docker container restart"
alias drm="docker container rm"
alias 'drm!'="docker container rm -f"
alias dst="docker container start"
alias dstp="docker container stop"
alias dsta="docker stop \$(docker ps -q)"
alias dtop="docker top"
alias dxc="docker container exec"
alias dxcit="docker container exec -it"

alias dib="docker image build"
alias dii="docker image inspect"
alias dils="docker image ls"
alias dipru="docker image prune -a"
alias dipu="docker image push"
alias dirm="docker image rm"

alias dnc="docker network create"
alias dncn="docker network connect"
alias dndcn="docker network disconnect"
alias dni="docker network inspect"
alias dnls="docker network ls"
alias dnprune="docker network prune"
alias dnrm="docker network rm"

alias dvi="docker volume inspect"
alias dvls="docker volume ls"
alias dvprune="docker volume prune"

alias dc="docker compose"
alias dco="docker compose"
alias dcb="docker compose build"
alias dcbuild="docker compose build"
alias dcup="docker compose up -d"
alias dcupd="docker compose up -d"
alias dcupb="docker compose up --build"
alias dcupdb="docker compose up -d --build"
alias dcdn="docker compose down"
alias dcdown="docker compose down"
alias dce="docker compose exec"
alias dcl="docker compose logs"
alias dclf="docker compose logs -f"
alias dclF="docker compose logs -f --tail 0"
alias dcps="docker compose ps"
alias dcpull="docker compose pull"
alias dcr="docker compose run"
alias dcrestart="docker compose restart"
alias dcrm="docker compose rm"
alias dcstart="docker compose start"
alias dcstop="docker compose stop"
alias dck="docker compose kill"

alias dsprune="docker system prune"
alias dcprune="docker container prune"

alias dlazydocker="docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock lazyteam/lazydocker"
